//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SENA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class practicas3Entities : DbContext
    {
        public practicas3Entities()
            : base("name=practicas3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Actitud_Comportamiento> Tbl_Actitud_Comportamiento { get; set; }
        public virtual DbSet<Tbl_Aprendices> Tbl_Aprendices { get; set; }
        public virtual DbSet<Tbl_Empresas> Tbl_Empresas { get; set; }
        public virtual DbSet<Tbl_Evaluacion_Etapa_Productiva> Tbl_Evaluacion_Etapa_Productiva { get; set; }
        public virtual DbSet<Tbl_Factores_Tecnicos> Tbl_Factores_Tecnicos { get; set; }
        public virtual DbSet<Tbl_Fichas> Tbl_Fichas { get; set; }
        public virtual DbSet<Tbl_Instructores> Tbl_Instructores { get; set; }
        public virtual DbSet<Tbl_Planeacion_Etapa_Productiva> Tbl_Planeacion_Etapa_Productiva { get; set; }
        public virtual DbSet<Tbl_Programas> Tbl_Programas { get; set; }
        public virtual DbSet<Tbl_Roles> Tbl_Roles { get; set; }
        public virtual DbSet<Tbl_Usuarios> Tbl_Usuarios { get; set; }
        public virtual DbSet<Tbl_Visitas> Tbl_Visitas { get; set; }
    }
}
