//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SENA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Factores_Tecnicos
    {
        public int Id_Factores_Tecnicos { get; set; }
        public Nullable<int> Tipo_Informe { get; set; }
        public string Transferencia_Conocimiento { get; set; }
        public string Valoracion_Conocimiento { get; set; }
        public string Mejora_Continua { get; set; }
        public string Valoracion_Mejora { get; set; }
        public string Fortalecimiento_Ocupacional { get; set; }
        public string Valoracion_Fortalecimiento { get; set; }
        public string Oportunidad_Calidad { get; set; }
        public string Valoracion_Oportunidad { get; set; }
        public string Responsabilidad_Ambiental { get; set; }
        public string Valoracion_Ambiental { get; set; }
        public string Administracion_Recursos { get; set; }
        public string Valoracion_Administracion { get; set; }
        public string Seguridad_Ocupacional { get; set; }
        public string Valoracion_Seguridad { get; set; }
        public string Documentacion_Etapa_Productiva { get; set; }
        public string Valoracion_Etapa_Productiva { get; set; }
        public string Observacion_Jefe { get; set; }
        public string Observacion_Aprendiz { get; set; }
        public Nullable<int> Id_Aprendiz { get; set; }
    
        public virtual Tbl_Aprendices Tbl_Aprendices { get; set; }
    }
}
