//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SENA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Instructores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Instructores()
        {
            this.Tbl_Visitas = new HashSet<Tbl_Visitas>();
        }
    
        [Required(ErrorMessage = "Campo obligatorio")]
        [RegularExpression(@"\d{7,}$",
            ErrorMessage = "Llene los campos de forma correcta <br/> " +
            "Las cadenas deben contener minimo 3 caracteres y los numeros minimo 7")]
        public int Numero_Identificacion { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [RegularExpression(@"^[a-zA-ZÀ-ÿ\u00f1\u00d1\s]{3,}$",
            ErrorMessage = "Llene los campos de forma correcta <br/> " +
            "Las cadenas deben contener minimo 3 caracteres y los numeros minimo 7")]
        public string Nombres { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [RegularExpression(@"^[a-zA-ZÀ-ÿ\u00f1\u00d1\s]{3,}$",
            ErrorMessage = "Llene los campos de forma correcta <br/> " +
            "Las cadenas deben contener minimo 3 caracteres y los numeros minimo 7")]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        [RegularExpression(@"^[a-zA-ZÀ-ÿ0-9\u00f1\u00d1\s]{3,}$",
            ErrorMessage = "Llene los campos de forma correcta <br/> " +
            "Las cadenas deben contener minimo 3 caracteres y los numeros minimo 7")]
        public string Id_Usuario { get; set; }
    
        public virtual Tbl_Usuarios Tbl_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Visitas> Tbl_Visitas { get; set; }
    }
}
