//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SENA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Planeacion_Etapa_Productiva
    {
        public int Id_Planeacion { get; set; }
        public string Actividades_A_Desarrollar { get; set; }
        public string Evidencias_Aprendizaje { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Lugar { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Id_Aprendiz { get; set; }
    
        public virtual Tbl_Aprendices Tbl_Aprendices { get; set; }
    }
}
